In [35]:
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import apriori,association_rules

In [36]:
data=pd.read_csv('C:\\Users\\vishw\\excelr drive files\\Assignments questions of excelr\\Association_rules\\book.csv')
data.head()

,ChildBks,YouthBks,CookBks,DoItYBks,RefBks,ArtBks,GeogBks,ItalCook,ItalAtlas,ItalArt,Florence
0,0,1,0,1,0,0,1,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0
3,1,1,1,0,1,0,1,0,0,0,0
4,0,0,1,0,0,0,1,0,0,0,0

since,the data is in the transaction formation.no necessary of using transaction encoder.

# Apriori algorithm

In [37]:
books=apriori(data,min_support=0.005,use_colnames=True)
books

      support                                           itemsets
0      0.4230                                         (ChildBks)
1      0.2475                                         (YouthBks)
2      0.4310                                          (CookBks)
3      0.2820                                         (DoItYBks)
4      0.2145                                           (RefBks)
...       ...                                                ...
1057   0.0060  (ItalCook, ChildBks, ItalArt, ArtBks, RefBks, ...
1058   0.0050  (ItalCook, ChildBks, GeogBks, ItalArt, ArtBks,...
1059   0.0065  (ItalCook, ChildBks, ItalArt, ArtBks, RefBks, ...
1060   0.0080  (ItalCook, GeogBks, ChildBks, ItalArt, ArtBks,...
1061   0.0050  (ItalCook, GeogBks, ItalArt, ArtBks, RefBks, C...

[1062 rows x 2 columns]

In [38]:
rules=association_rules(books,metric="lift",min_threshold=1)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(YouthBks),(ChildBks),0.2475,0.4230,0.165,0.666667,1.576044,0.060308,1.731000
1,(ChildBks),(YouthBks),0.4230,0.2475,0.165,0.390071,1.576044,0.060308,1.233750
2,(ChildBks),(CookBks),0.4230,0.4310,0.256,0.605201,1.404179,0.073687,1.441240
3,(CookBks),(ChildBks),0.4310,0.4230,0.256,0.593968,1.404179,0.073687,1.421069
4,(ChildBks),(DoItYBks),0.4230,0.2820,0.184,0.434988,1.542511,0.064714,1.270770
...,...,...,...,...,...,...,...,...,...
35293,(ArtBks),"(ItalCook, GeogBks, ItalArt, RefBks, CookBks, ...",0.2410,0.0050,0.005,0.020747,4.149378,0.003795,1.016081
35294,(RefBks),"(ItalCook, GeogBks, ItalArt, ArtBks, CookBks, ...",0.2145,0.0050,0.005,0.023310,4.662005,0.003928,1.018747
35295,(CookBks),"(ItalCook, GeogBks, ItalArt, ArtBks, RefBks, I...",0.4310,0.0050,0.005,0.011601,2.320186,0.002845,1.006678
35296,(ItalAtlas),"(ItalCook, GeogBks, ItalArt, ArtBks, RefBks, C...",0.0370,0.0055,0.005,0.135135,24.570025,0.004797,1.149891
35297,(DoItYBks),"(ItalCook, GeogBks, ItalArt, ArtBks, RefBks, C...",0.2820,0.0090,0.005,0.017730,1.970055,0.002462,1.008888

In [39]:
rules.sort_values('lift',ascending=False,)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
35219,"(ArtBks, ItalCook, ItalAtlas)","(GeogBks, ItalArt, RefBks, CookBks, DoItYBks)",0.0130,0.0055,0.0050,0.384615,69.930070,0.004928,1.616062
35122,"(GeogBks, ItalArt, RefBks, CookBks, DoItYBks)","(ArtBks, ItalCook, ItalAtlas)",0.0055,0.0130,0.0050,0.909091,69.930070,0.004928,10.857000
35255,"(ArtBks, CookBks, ItalAtlas)","(ItalCook, GeogBks, ItalArt, RefBks, DoItYBks)",0.0140,0.0055,0.0050,0.357143,64.935065,0.004923,1.547000
35086,"(ItalCook, GeogBks, ItalArt, RefBks, DoItYBks)","(ArtBks, CookBks, ItalAtlas)",0.0055,0.0140,0.0050,0.909091,64.935065,0.004923,10.846000
33192,"(ItalArt, RefBks, GeogBks, DoItYBks)","(ArtBks, ItalCook, ItalAtlas)",0.0060,0.0130,0.0050,0.833333,64.102564,0.004922,5.922000
...,...,...,...,...,...,...,...,...,...
5349,(Florence),"(YouthBks, RefBks, ChildBks, CookBks)",0.1085,0.0680,0.0075,0.069124,1.016536,0.000122,1.001208
51,(CookBks),(Florence),0.4310,0.1085,0.0475,0.110209,1.015749,0.000737,1.001920
50,(Florence),(CookBks),0.1085,0.4310,0.0475,0.437788,1.015749,0.000737,1.012074
5141,"(YouthBks, ChildBks, CookBks, DoItYBks)",(Florence),0.0820,0.1085,0.0090,0.109756,1.011577,0.000103,1.001411
5168,(Florence),"(YouthBks, ChildBks, CookBks, DoItYBks)",0.1085,0.0820,0.0090,0.082949,1.011577,0.000103,1.001035

In [40]:
rules.sort_values('lift',ascending = False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
35219,"(ArtBks, ItalCook, ItalAtlas)","(GeogBks, ItalArt, RefBks, CookBks, DoItYBks)",0.0130,0.0055,0.0050,0.384615,69.930070,0.004928,1.616062
35122,"(GeogBks, ItalArt, RefBks, CookBks, DoItYBks)","(ArtBks, ItalCook, ItalAtlas)",0.0055,0.0130,0.0050,0.909091,69.930070,0.004928,10.857000
35255,"(ArtBks, CookBks, ItalAtlas)","(ItalCook, GeogBks, ItalArt, RefBks, DoItYBks)",0.0140,0.0055,0.0050,0.357143,64.935065,0.004923,1.547000
35086,"(ItalCook, GeogBks, ItalArt, RefBks, DoItYBks)","(ArtBks, CookBks, ItalAtlas)",0.0055,0.0140,0.0050,0.909091,64.935065,0.004923,10.846000
33192,"(ItalArt, RefBks, GeogBks, DoItYBks)","(ArtBks, ItalCook, ItalAtlas)",0.0060,0.0130,0.0050,0.833333,64.102564,0.004922,5.922000
...,...,...,...,...,...,...,...,...,...
5349,(Florence),"(YouthBks, RefBks, ChildBks, CookBks)",0.1085,0.0680,0.0075,0.069124,1.016536,0.000122,1.001208
51,(CookBks),(Florence),0.4310,0.1085,0.0475,0.110209,1.015749,0.000737,1.001920
50,(Florence),(CookBks),0.1085,0.4310,0.0475,0.437788,1.015749,0.000737,1.012074
5141,"(YouthBks, ChildBks, CookBks, DoItYBks)",(Florence),0.0820,0.1085,0.0090,0.109756,1.011577,0.000103,1.001411
5168,(Florence),"(YouthBks, ChildBks, CookBks, DoItYBks)",0.1085,0.0820,0.0090,0.082949,1.011577,0.000103,1.001035

In [41]:
rules[rules.lift>=6]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
98,(ItalArt),(ItalCook),0.0485,0.1135,0.0375,0.773196,6.812298,0.031995,3.908659
99,(ItalCook),(ItalArt),0.1135,0.0485,0.0375,0.330396,6.812298,0.031995,1.420990
102,(ItalArt),(ItalAtlas),0.0485,0.0370,0.0165,0.340206,9.194762,0.014706,1.459547
103,(ItalAtlas),(ItalArt),0.0370,0.0485,0.0165,0.445946,9.194762,0.014706,1.717341
340,"(ItalCook, ChildBks)",(ItalAtlas),0.0850,0.0370,0.0200,0.235294,6.359300,0.016855,1.259308
...,...,...,...,...,...,...,...,...,...
35287,"(CookBks, ItalAtlas)","(ItalCook, GeogBks, ItalArt, ArtBks, RefBks, D...",0.0285,0.0055,0.0050,0.175439,31.897927,0.004843,1.206096
35289,"(DoItYBks, ItalAtlas)","(ItalCook, GeogBks, ItalArt, ArtBks, RefBks, C...",0.0190,0.0110,0.0050,0.263158,23.923445,0.004791,1.342214
35290,(ItalCook),"(GeogBks, ItalArt, ArtBks, RefBks, CookBks, It...",0.1135,0.0050,0.0050,0.044053,8.810573,0.004432,1.040853
35292,(ItalArt),"(ItalCook, GeogBks, ArtBks, RefBks, CookBks, I...",0.0485,0.0050,0.0050,0.103093,20.618557,0.004758,1.109368
35296,(ItalAtlas),"(ItalCook, GeogBks, ItalArt, ArtBks, RefBks, C...",0.0370,0.0055,0.0050,0.135135,24.570025,0.004797,1.149891

In [42]:
rules[rules.confidence>=0.8]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
44,(ItalCook),(CookBks),0.1135,0.4310,0.1135,1.000000,2.320186,0.064582,inf
48,(ItalArt),(CookBks),0.0485,0.4310,0.0410,0.845361,1.961394,0.020096,3.679533
73,(ItalAtlas),(RefBks),0.0370,0.2145,0.0370,1.000000,4.662005,0.029063,inf
84,(ItalArt),(ArtBks),0.0485,0.2410,0.0485,1.000000,4.149378,0.036812,inf
115,"(YouthBks, DoItYBks)",(ChildBks),0.1155,0.4230,0.0950,0.822511,1.944470,0.046143,3.250902
...,...,...,...,...,...,...,...,...,...
35127,"(GeogBks, ArtBks, RefBks, ItalAtlas, DoItYBks)","(ItalArt, ItalCook, CookBks)",0.0055,0.0375,0.0050,0.909091,24.242424,0.004794,10.587500
35128,"(GeogBks, ArtBks, CookBks, ItalAtlas, DoItYBks)","(ItalArt, RefBks, ItalCook)",0.0050,0.0160,0.0050,1.000000,62.500000,0.004920,inf
35177,"(ItalArt, RefBks, GeogBks, DoItYBks)","(ArtBks, ItalCook, CookBks, ItalAtlas)",0.0060,0.0130,0.0050,0.833333,64.102564,0.004922,5.922000
35180,"(ItalArt, DoItYBks, GeogBks, ItalAtlas)","(ArtBks, RefBks, ItalCook, CookBks)",0.0055,0.0235,0.0050,0.909091,38.684720,0.004871,10.741500
35186,"(ArtBks, DoItYBks, GeogBks, ItalAtlas)","(ItalArt, RefBks, ItalCook, CookBks)",0.0055,0.0160,0.0050,0.909091,56.818182,0.004912,10.824000